/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package aragon.ico.contacto;

import java.awt.Color;
import java.awt.Image;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import Animacion.Animacion;
import aragon.ico.Inicio;
import aragon.ico.Salida;
import aragon.ico.ingSoft.IngSoftConceptos;
import aragon.ico.scrum.Agil;
import aragon.ico.scrum.Scrum;
import java.awt.Desktop;
import java.net.URI;
import java.util.Timer;
import java.util.TimerTask;

/**
 *
 * @author Muffin
 */
public class ContactoScrum_Team extends javax.swing.JFrame {

    Timer timerControl;
    TimerTask controlmenu;
    
    /**
     * Creates new form ContactoMarco
     */
    public ContactoScrum_Team() {
        initComponents();
        
        // La ventana se centrará en medio de la pantalla
        this.setLocationRelativeTo(null);
        
        setIconImage(new ImageIcon(System.getProperty("user.dir") + "/src/aragon/ico/imagenes/inicio/ICO.png").getImage());
        
        // Los menus desplegables iniciaran ocultos
        jPDesplegableDAScrum.setVisible(false);
        jPDesplegableContacto.setVisible(false);
        
        // Iniciar el Timer
        controlDesplegable();
        
        ponerImagenes();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jPanel1 = new javax.swing.JPanel();
        jPBarraMenu = new javax.swing.JPanel();
        jLLogoICO = new javax.swing.JLabel();
        jBIng_Soft = new javax.swing.JButton();
        jBInicio = new javax.swing.JButton();
        jBDA_Scrum = new javax.swing.JButton();
        jBContacto = new javax.swing.JButton();
        jBSalir = new javax.swing.JButton();
        jPDesplegableDAScrum = new javax.swing.JPanel();
        jBDAgil = new javax.swing.JButton();
        jBScrum = new javax.swing.JButton();
        jPDesplegableContacto = new javax.swing.JPanel();
        jBProduct_Owner = new javax.swing.JButton();
        jBScrum_Master = new javax.swing.JButton();
        jBScrum_Team = new javax.swing.JButton();
        jPInformacionProduct_Owner = new javax.swing.JPanel();
        jLHeader = new javax.swing.JLabel();
        jLMiembro_Equipo = new javax.swing.JLabel();
        jPerfilGiovanni = new javax.swing.JPanel();
        jLFotoGiovanni = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jPInformacionGiovanni = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLCine = new javax.swing.JLabel();
        jLTacos = new javax.swing.JLabel();
        jLLMusica = new javax.swing.JLabel();
        jLVideoJuegos = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLFacebookG = new javax.swing.JLabel();
        jLTwitterG = new javax.swing.JLabel();
        jLInstagramG = new javax.swing.JLabel();
        jLGithubG = new javax.swing.JLabel();
        jLDormir = new javax.swing.JLabel();
        jPerfilMarco = new javax.swing.JPanel();
        jLFotoMarco = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jPInformacionMarco = new javax.swing.JPanel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLGoku = new javax.swing.JLabel();
        jLSpider = new javax.swing.JLabel();
        jLGuitarra = new javax.swing.JLabel();
        jLGames = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLFacebookM = new javax.swing.JLabel();
        jLTwitterM = new javax.swing.JLabel();
        jLGithubM = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Scrum Master");
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jScrollPane1.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);

        jPanel1.setPreferredSize(new java.awt.Dimension(1200, 1600));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPBarraMenu.setBackground(new java.awt.Color(245, 245, 245));

        jBIng_Soft.setFont(new java.awt.Font("Berlin Sans FB", 0, 24)); // NOI18N
        jBIng_Soft.setForeground(java.awt.Color.gray);
        jBIng_Soft.setText("Ingeniería de Software");
        jBIng_Soft.setBorder(null);
        jBIng_Soft.setBorderPainted(false);
        jBIng_Soft.setContentAreaFilled(false);
        jBIng_Soft.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jBIng_Soft.setFocusPainted(false);
        jBIng_Soft.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jBIng_SoftMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jBIng_SoftMouseExited(evt);
            }
        });
        jBIng_Soft.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBIng_SoftActionPerformed(evt);
            }
        });

        jBInicio.setFont(new java.awt.Font("Berlin Sans FB", 0, 24)); // NOI18N
        jBInicio.setForeground(java.awt.Color.gray);
        jBInicio.setText("Inicio");
        jBInicio.setBorder(null);
        jBInicio.setBorderPainted(false);
        jBInicio.setContentAreaFilled(false);
        jBInicio.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jBInicio.setFocusPainted(false);
        jBInicio.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jBInicioMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jBInicioMouseExited(evt);
            }
        });
        jBInicio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBInicioActionPerformed(evt);
            }
        });

        jBDA_Scrum.setFont(new java.awt.Font("Berlin Sans FB", 0, 24)); // NOI18N
        jBDA_Scrum.setForeground(java.awt.Color.gray);
        jBDA_Scrum.setText("Desarrollo Ágil y Scrum");
        jBDA_Scrum.setBorder(null);
        jBDA_Scrum.setBorderPainted(false);
        jBDA_Scrum.setContentAreaFilled(false);
        jBDA_Scrum.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jBDA_Scrum.setFocusPainted(false);
        jBDA_Scrum.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jBDA_ScrumMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jBDA_ScrumMouseExited(evt);
            }
        });
        jBDA_Scrum.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBDA_ScrumActionPerformed(evt);
            }
        });

        jBContacto.setFont(new java.awt.Font("Berlin Sans FB", 0, 24)); // NOI18N
        jBContacto.setForeground(java.awt.Color.gray);
        jBContacto.setText("Contacto");
        jBContacto.setBorder(null);
        jBContacto.setBorderPainted(false);
        jBContacto.setContentAreaFilled(false);
        jBContacto.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jBContacto.setFocusPainted(false);
        jBContacto.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jBContactoMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jBContactoMouseExited(evt);
            }
        });
        jBContacto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBContactoActionPerformed(evt);
            }
        });

        jBSalir.setFont(new java.awt.Font("Berlin Sans FB", 0, 24)); // NOI18N
        jBSalir.setForeground(java.awt.Color.gray);
        jBSalir.setText("Salir");
        jBSalir.setBorder(null);
        jBSalir.setBorderPainted(false);
        jBSalir.setContentAreaFilled(false);
        jBSalir.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jBSalir.setFocusPainted(false);
        jBSalir.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jBSalirMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jBSalirMouseExited(evt);
            }
        });
        jBSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBSalirActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPBarraMenuLayout = new javax.swing.GroupLayout(jPBarraMenu);
        jPBarraMenu.setLayout(jPBarraMenuLayout);
        jPBarraMenuLayout.setHorizontalGroup(
            jPBarraMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPBarraMenuLayout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addComponent(jLLogoICO, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 278, Short.MAX_VALUE)
                .addComponent(jBInicio)
                .addGap(30, 30, 30)
                .addComponent(jBIng_Soft)
                .addGap(30, 30, 30)
                .addComponent(jBDA_Scrum)
                .addGap(30, 30, 30)
                .addComponent(jBContacto)
                .addGap(30, 30, 30)
                .addComponent(jBSalir)
                .addGap(50, 50, 50))
        );
        jPBarraMenuLayout.setVerticalGroup(
            jPBarraMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPBarraMenuLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPBarraMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(jBInicio)
                    .addComponent(jBIng_Soft)
                    .addComponent(jBDA_Scrum)
                    .addComponent(jBContacto)
                    .addComponent(jBSalir)
                    .addComponent(jLLogoICO, javax.swing.GroupLayout.DEFAULT_SIZE, 68, Short.MAX_VALUE))
                .addContainerGap())
        );

        jPanel1.add(jPBarraMenu, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1200, 90));

        jPDesplegableDAScrum.setBackground(new java.awt.Color(245, 245, 245));

        jBDAgil.setFont(new java.awt.Font("Berlin Sans FB", 0, 18)); // NOI18N
        jBDAgil.setForeground(java.awt.Color.gray);
        jBDAgil.setText("Desarrollo Ágil");
        jBDAgil.setBorder(null);
        jBDAgil.setBorderPainted(false);
        jBDAgil.setContentAreaFilled(false);
        jBDAgil.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jBDAgil.setFocusPainted(false);
        jBDAgil.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jBDAgil.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jBDAgil.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jBDAgilMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jBDAgilMouseExited(evt);
            }
        });
        jBDAgil.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBDAgilActionPerformed(evt);
            }
        });

        jBScrum.setFont(new java.awt.Font("Berlin Sans FB", 0, 18)); // NOI18N
        jBScrum.setForeground(java.awt.Color.gray);
        jBScrum.setText("Scrum");
        jBScrum.setBorder(null);
        jBScrum.setBorderPainted(false);
        jBScrum.setContentAreaFilled(false);
        jBScrum.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jBScrum.setFocusPainted(false);
        jBScrum.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jBScrum.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jBScrum.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jBScrumMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jBScrumMouseExited(evt);
            }
        });
        jBScrum.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBScrumActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPDesplegableDAScrumLayout = new javax.swing.GroupLayout(jPDesplegableDAScrum);
        jPDesplegableDAScrum.setLayout(jPDesplegableDAScrumLayout);
        jPDesplegableDAScrumLayout.setHorizontalGroup(
            jPDesplegableDAScrumLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPDesplegableDAScrumLayout.createSequentialGroup()
                .addContainerGap(70, Short.MAX_VALUE)
                .addGroup(jPDesplegableDAScrumLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jBDAgil, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jBScrum, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
        jPDesplegableDAScrumLayout.setVerticalGroup(
            jPDesplegableDAScrumLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPDesplegableDAScrumLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jBDAgil)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jBScrum)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel1.add(jPDesplegableDAScrum, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 20, 240, 70));

        jPDesplegableContacto.setBackground(new java.awt.Color(245, 245, 245));

        jBProduct_Owner.setFont(new java.awt.Font("Berlin Sans FB", 0, 18)); // NOI18N
        jBProduct_Owner.setForeground(java.awt.Color.gray);
        jBProduct_Owner.setText("Product Owner");
        jBProduct_Owner.setBorder(null);
        jBProduct_Owner.setBorderPainted(false);
        jBProduct_Owner.setContentAreaFilled(false);
        jBProduct_Owner.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jBProduct_Owner.setFocusPainted(false);
        jBProduct_Owner.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jBProduct_Owner.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jBProduct_OwnerMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jBProduct_OwnerMouseExited(evt);
            }
        });
        jBProduct_Owner.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBProduct_OwnerActionPerformed(evt);
            }
        });

        jBScrum_Master.setFont(new java.awt.Font("Berlin Sans FB", 0, 18)); // NOI18N
        jBScrum_Master.setForeground(java.awt.Color.gray);
        jBScrum_Master.setText("Scrum Master");
        jBScrum_Master.setBorder(null);
        jBScrum_Master.setBorderPainted(false);
        jBScrum_Master.setContentAreaFilled(false);
        jBScrum_Master.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jBScrum_Master.setFocusPainted(false);
        jBScrum_Master.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jBScrum_Master.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jBScrum_MasterMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jBScrum_MasterMouseExited(evt);
            }
        });
        jBScrum_Master.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBScrum_MasterActionPerformed(evt);
            }
        });

        jBScrum_Team.setFont(new java.awt.Font("Berlin Sans FB", 0, 18)); // NOI18N
        jBScrum_Team.setForeground(java.awt.Color.gray);
        jBScrum_Team.setText("Scrum Team");
        jBScrum_Team.setBorder(null);
        jBScrum_Team.setBorderPainted(false);
        jBScrum_Team.setContentAreaFilled(false);
        jBScrum_Team.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jBScrum_Team.setFocusPainted(false);
        jBScrum_Team.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jBScrum_Team.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jBScrum_TeamMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jBScrum_TeamMouseExited(evt);
            }
        });

        javax.swing.GroupLayout jPDesplegableContactoLayout = new javax.swing.GroupLayout(jPDesplegableContacto);
        jPDesplegableContacto.setLayout(jPDesplegableContactoLayout);
        jPDesplegableContactoLayout.setHorizontalGroup(
            jPDesplegableContactoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPDesplegableContactoLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPDesplegableContactoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jBProduct_Owner, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jBScrum_Master, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jBScrum_Team, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
        jPDesplegableContactoLayout.setVerticalGroup(
            jPDesplegableContactoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPDesplegableContactoLayout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addComponent(jBProduct_Owner)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jBScrum_Master)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jBScrum_Team)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel1.add(jPDesplegableContacto, new org.netbeans.lib.awtextra.AbsoluteConstraints(930, 0, 160, 90));

        jPInformacionProduct_Owner.setBackground(new java.awt.Color(17, 134, 198));
        jPInformacionProduct_Owner.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPInformacionProduct_Owner.add(jLHeader, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1200, 250));

        jLMiembro_Equipo.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 24)); // NOI18N
        jLMiembro_Equipo.setForeground(new java.awt.Color(255, 255, 255));
        jLMiembro_Equipo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLMiembro_Equipo.setText("Scrum Team");
        jPInformacionProduct_Owner.add(jLMiembro_Equipo, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 300, 1180, -1));

        jPerfilGiovanni.setBackground(new java.awt.Color(26, 82, 118));

        jLabel1.setFont(new java.awt.Font("Berlin Sans FB", 0, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Sánchez Solano Geovanni");

        jLabel2.setFont(new java.awt.Font("Berlin Sans FB", 0, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("No. de Cuenta: 318207825");

        jLabel3.setFont(new java.awt.Font("Berlin Sans FB", 0, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Email: geovannisans74@gmail.com");

        jLabel4.setFont(new java.awt.Font("Berlin Sans FB", 0, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("Semestre: 6° Semestre");

        javax.swing.GroupLayout jPerfilGiovanniLayout = new javax.swing.GroupLayout(jPerfilGiovanni);
        jPerfilGiovanni.setLayout(jPerfilGiovanniLayout);
        jPerfilGiovanniLayout.setHorizontalGroup(
            jPerfilGiovanniLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPerfilGiovanniLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPerfilGiovanniLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPerfilGiovanniLayout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPerfilGiovanniLayout.createSequentialGroup()
                        .addGap(0, 35, Short.MAX_VALUE)
                        .addComponent(jLFotoGiovanni, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(45, 45, 45))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPerfilGiovanniLayout.createSequentialGroup()
                        .addGroup(jPerfilGiovanniLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addContainerGap())))
        );
        jPerfilGiovanniLayout.setVerticalGroup(
            jPerfilGiovanniLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPerfilGiovanniLayout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addComponent(jLFotoGiovanni, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2)
                .addGap(25, 25, 25)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel4)
                .addContainerGap(75, Short.MAX_VALUE))
        );

        jPInformacionProduct_Owner.add(jPerfilGiovanni, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 365, 350, 500));

        jPInformacionGiovanni.setBackground(new java.awt.Color(255, 255, 255));

        jLabel5.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 24)); // NOI18N
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("Redes Sociales");

        jLabel6.setFont(new java.awt.Font("Berlin Sans FB", 0, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(59, 59, 59));
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("Me encanta ir al cine, salir con mis amigos, comer tacos,");

        jLabel7.setFont(new java.awt.Font("Berlin Sans FB", 0, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(59, 59, 59));
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setText("escuchar música, jugar videojuegos y dormir.");

        jLabel9.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 24)); // NOI18N
        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel9.setText("Hobbies");

        jLFacebookG.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLFacebookG.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLFacebookGMouseClicked(evt);
            }
        });

        jLTwitterG.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLTwitterG.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLTwitterGMouseClicked(evt);
            }
        });

        jLInstagramG.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLInstagramG.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLInstagramGMouseClicked(evt);
            }
        });

        jLGithubG.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLGithubG.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLGithubGMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPInformacionGiovanniLayout = new javax.swing.GroupLayout(jPInformacionGiovanni);
        jPInformacionGiovanni.setLayout(jPInformacionGiovanniLayout);
        jPInformacionGiovanniLayout.setHorizontalGroup(
            jPInformacionGiovanniLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPInformacionGiovanniLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(jPInformacionGiovanniLayout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(jLCine, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29)
                .addComponent(jLTacos, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 30, Short.MAX_VALUE)
                .addComponent(jLLMusica, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29)
                .addComponent(jLVideoJuegos, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29)
                .addComponent(jLDormir, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29))
            .addGroup(jPInformacionGiovanniLayout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addGroup(jPInformacionGiovanniLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 470, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPInformacionGiovanniLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 471, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPInformacionGiovanniLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLFacebookG, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(34, 34, 34)
                .addComponent(jLTwitterG, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(34, 34, 34)
                .addComponent(jLInstagramG, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(35, 35, 35)
                .addComponent(jLGithubG, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(70, 70, 70))
        );
        jPInformacionGiovanniLayout.setVerticalGroup(
            jPInformacionGiovanniLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPInformacionGiovanniLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel9)
                .addGap(18, 18, 18)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel7)
                .addGap(26, 26, 26)
                .addGroup(jPInformacionGiovanniLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(jLDormir, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLVideoJuegos, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLLMusica, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLTacos, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLCine, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(51, 51, 51)
                .addComponent(jLabel5)
                .addGap(34, 34, 34)
                .addGroup(jPInformacionGiovanniLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(jLTwitterG, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLFacebookG, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLInstagramG, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLGithubG, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(129, 129, 129))
        );

        jPInformacionProduct_Owner.add(jPInformacionGiovanni, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 365, 550, 500));

        jPerfilMarco.setBackground(new java.awt.Color(26, 82, 118));

        jLabel8.setFont(new java.awt.Font("Berlin Sans FB", 0, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setText("Nava Cruz Marco Antonio");

        jLabel10.setFont(new java.awt.Font("Berlin Sans FB", 0, 14)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel10.setText("No. de Cuenta: 313166129");

        jLabel11.setFont(new java.awt.Font("Berlin Sans FB", 0, 14)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel11.setText("Email: marconava2410@gmail.com");

        jLabel12.setFont(new java.awt.Font("Berlin Sans FB", 0, 14)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel12.setText("Semestre: 6° Semestre");

        javax.swing.GroupLayout jPerfilMarcoLayout = new javax.swing.GroupLayout(jPerfilMarco);
        jPerfilMarco.setLayout(jPerfilMarcoLayout);
        jPerfilMarcoLayout.setHorizontalGroup(
            jPerfilMarcoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPerfilMarcoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPerfilMarcoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPerfilMarcoLayout.createSequentialGroup()
                        .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPerfilMarcoLayout.createSequentialGroup()
                        .addGap(0, 35, Short.MAX_VALUE)
                        .addComponent(jLFotoMarco, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(45, 45, 45))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPerfilMarcoLayout.createSequentialGroup()
                        .addGroup(jPerfilMarcoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel12, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel11, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addContainerGap())))
        );
        jPerfilMarcoLayout.setVerticalGroup(
            jPerfilMarcoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPerfilMarcoLayout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addComponent(jLFotoMarco, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel10)
                .addGap(25, 25, 25)
                .addComponent(jLabel11)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel12)
                .addContainerGap(75, Short.MAX_VALUE))
        );

        jPInformacionProduct_Owner.add(jPerfilMarco, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 950, 350, 500));

        jPInformacionMarco.setBackground(new java.awt.Color(255, 255, 255));

        jLabel13.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 24)); // NOI18N
        jLabel13.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel13.setText("Redes Sociales");

        jLabel14.setFont(new java.awt.Font("Berlin Sans FB", 0, 18)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(59, 59, 59));
        jLabel14.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel14.setText("Me agrada estar solo pero no desprecio la compañia de otras");

        jLabel15.setFont(new java.awt.Font("Berlin Sans FB", 0, 18)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(59, 59, 59));
        jLabel15.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel15.setText("personas, ver anime o películas en las noches, también leo");

        jLabel16.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 24)); // NOI18N
        jLabel16.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel16.setText("Hobbies");

        jLFacebookM.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLFacebookM.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLFacebookMMouseClicked(evt);
            }
        });

        jLTwitterM.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLTwitterM.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLTwitterMMouseClicked(evt);
            }
        });

        jLGithubM.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLGithubM.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLGithubMMouseClicked(evt);
            }
        });

        jLabel17.setFont(new java.awt.Font("Berlin Sans FB", 0, 18)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(59, 59, 59));
        jLabel17.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel17.setText("mangas y unos cuantos comics, escuchar música, comer y los");

        jLabel18.setFont(new java.awt.Font("Berlin Sans FB", 0, 18)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(59, 59, 59));
        jLabel18.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel18.setText("videojuegos.");

        javax.swing.GroupLayout jPInformacionMarcoLayout = new javax.swing.GroupLayout(jPInformacionMarco);
        jPInformacionMarco.setLayout(jPInformacionMarcoLayout);
        jPInformacionMarcoLayout.setHorizontalGroup(
            jPInformacionMarcoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPInformacionMarcoLayout.createSequentialGroup()
                .addGroup(jPInformacionMarcoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPInformacionMarcoLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPInformacionMarcoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel13, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel16, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel14, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel15, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel17, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel18, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(jPInformacionMarcoLayout.createSequentialGroup()
                        .addGap(50, 50, 50)
                        .addComponent(jLGoku, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(50, 50, 50)
                        .addComponent(jLSpider, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(50, 50, 50)
                        .addComponent(jLGuitarra, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(50, 50, 50)
                        .addComponent(jLGames, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 40, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPInformacionMarcoLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLFacebookM, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(50, 50, 50)
                .addComponent(jLTwitterM, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(50, 50, 50)
                .addComponent(jLGithubM, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(111, 111, 111))
        );
        jPInformacionMarcoLayout.setVerticalGroup(
            jPInformacionMarcoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPInformacionMarcoLayout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(jLabel16)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel14)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel15)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel17)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel18)
                .addGap(18, 18, 18)
                .addGroup(jPInformacionMarcoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(jLGames, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLGuitarra, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLSpider, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLGoku, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(51, 51, 51)
                .addComponent(jLabel13)
                .addGap(31, 31, 31)
                .addGroup(jPInformacionMarcoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(jLTwitterM, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLFacebookM, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLGithubM, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(54, Short.MAX_VALUE))
        );

        jPInformacionProduct_Owner.add(jPInformacionMarco, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 950, 550, 500));

        jPanel1.add(jPInformacionProduct_Owner, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 90, 1200, 1510));

        jScrollPane1.setViewportView(jPanel1);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1200, 720));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jBIng_SoftMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBIng_SoftMouseEntered
        jBIng_Soft.setForeground(Color.DARK_GRAY);
    }//GEN-LAST:event_jBIng_SoftMouseEntered

    private void jBIng_SoftMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBIng_SoftMouseExited
        jBIng_Soft.setForeground(Color.GRAY);
    }//GEN-LAST:event_jBIng_SoftMouseExited

    private void jBInicioMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBInicioMouseEntered
        jBInicio.setForeground(Color.DARK_GRAY);
    }//GEN-LAST:event_jBInicioMouseEntered

    private void jBInicioMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBInicioMouseExited
        jBInicio.setForeground(Color.GRAY);
    }//GEN-LAST:event_jBInicioMouseExited

    private void jBIng_SoftActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBIng_SoftActionPerformed
        IngSoftConceptos isc = new IngSoftConceptos();
        timerControl.cancel();
        this.setVisible(false);
        isc.setVisible(true);
        dispose();
    }//GEN-LAST:event_jBIng_SoftActionPerformed

    private void jBDA_ScrumMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBDA_ScrumMouseEntered
        jBDA_Scrum.setForeground(Color.DARK_GRAY);
    }//GEN-LAST:event_jBDA_ScrumMouseEntered

    private void jBDA_ScrumMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBDA_ScrumMouseExited
        jBDA_Scrum.setForeground(Color.GRAY);
    }//GEN-LAST:event_jBDA_ScrumMouseExited

    private void jBDA_ScrumActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBDA_ScrumActionPerformed
        int posicion = jPDesplegableDAScrum.getY();
        if (posicion < 90) {
            if (jPDesplegableContacto.isVisible()) {
                jPDesplegableContacto.setVisible(false);
            }
            jPDesplegableDAScrum.setVisible(true);
            Animacion.bajar(20, 90, 1, jPDesplegableDAScrum);
        }
        else{
            Animacion.subir(90, 20, 1, jPDesplegableDAScrum);
            jPDesplegableDAScrum.setVisible(false);
        }
    }//GEN-LAST:event_jBDA_ScrumActionPerformed

    private void jBContactoMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBContactoMouseEntered
        jBContacto.setForeground(Color.DARK_GRAY);
    }//GEN-LAST:event_jBContactoMouseEntered

    private void jBContactoMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBContactoMouseExited
        jBContacto.setForeground(Color.GRAY);
    }//GEN-LAST:event_jBContactoMouseExited

    private void jBContactoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBContactoActionPerformed
        int posicion = jPDesplegableContacto.getY();
        if (posicion < 90) {
            if (jPDesplegableDAScrum.isVisible()) {
                jPDesplegableDAScrum.setVisible(false);
            }
            jPDesplegableContacto.setVisible(true);
            Animacion.bajar(0, 90, 1, jPDesplegableContacto);
        }
        else{
            Animacion.subir(90, 0, 1, jPDesplegableContacto);
            jPDesplegableContacto.setVisible(false);
        }
    }//GEN-LAST:event_jBContactoActionPerformed

    private void jBSalirMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBSalirMouseEntered
        jBSalir.setForeground(Color.DARK_GRAY);
    }//GEN-LAST:event_jBSalirMouseEntered

    private void jBSalirMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBSalirMouseExited
        jBSalir.setForeground(Color.GRAY);
    }//GEN-LAST:event_jBSalirMouseExited

    private void jBSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBSalirActionPerformed
        Salida salir = new Salida();
        timerControl.cancel();
        this.setVisible(false);
        salir.setVisible(true);
        dispose();
    }//GEN-LAST:event_jBSalirActionPerformed

    private void jBDAgilMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBDAgilMouseEntered
        if (jPDesplegableDAScrum.isVisible()) {
            jBDAgil.setForeground(Color.DARK_GRAY);
        }
    }//GEN-LAST:event_jBDAgilMouseEntered

    private void jBDAgilMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBDAgilMouseExited
        if (jPDesplegableDAScrum.isVisible()) {
            jBDAgil.setForeground(Color.GRAY);
        }
    }//GEN-LAST:event_jBDAgilMouseExited

    private void jBScrumMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBScrumMouseEntered
        if (jPDesplegableDAScrum.isVisible()) {
            jBScrum.setForeground(Color.DARK_GRAY);
        }
    }//GEN-LAST:event_jBScrumMouseEntered

    private void jBScrumMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBScrumMouseExited
        if (jPDesplegableDAScrum.isVisible()) {
            jBScrum.setForeground(Color.GRAY);
        }
    }//GEN-LAST:event_jBScrumMouseExited

    private void jBProduct_OwnerMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBProduct_OwnerMouseEntered
        if (jPDesplegableContacto.isVisible()) {
            jBProduct_Owner.setForeground(Color.DARK_GRAY);
        }
    }//GEN-LAST:event_jBProduct_OwnerMouseEntered

    private void jBProduct_OwnerMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBProduct_OwnerMouseExited
        if (jPDesplegableContacto.isVisible()) {
            jBProduct_Owner.setForeground(Color.GRAY);
        }
    }//GEN-LAST:event_jBProduct_OwnerMouseExited

    private void jBScrum_MasterMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBScrum_MasterMouseEntered
        if (jPDesplegableContacto.isVisible()) {
            jBScrum_Master.setForeground(Color.DARK_GRAY);
        }
    }//GEN-LAST:event_jBScrum_MasterMouseEntered

    private void jBScrum_MasterMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBScrum_MasterMouseExited
        if (jPDesplegableContacto.isVisible()) {
            jBScrum_Master.setForeground(Color.GRAY);
        }
    }//GEN-LAST:event_jBScrum_MasterMouseExited

    private void jBScrum_TeamMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBScrum_TeamMouseEntered
        if (jPDesplegableContacto.isVisible()) {
            jBScrum_Team.setForeground(Color.DARK_GRAY);
        }
    }//GEN-LAST:event_jBScrum_TeamMouseEntered

    private void jBScrum_TeamMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBScrum_TeamMouseExited
        if (jPDesplegableContacto.isVisible()) {
            jBScrum_Team.setForeground(Color.GRAY);
        }
    }//GEN-LAST:event_jBScrum_TeamMouseExited

    private void jLFacebookGMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLFacebookGMouseClicked
        try {
            if (Desktop.isDesktopSupported()) {
                Desktop desktop = Desktop.getDesktop();
                if (desktop.isSupported(Desktop.Action.BROWSE)) {
                    desktop.browse(new URI("https://www.facebook.com/MuffinSanchez"));
                }
            }
        } catch (Exception e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_jLFacebookGMouseClicked

    private void jLTwitterGMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLTwitterGMouseClicked
        try {
            if (Desktop.isDesktopSupported()) {
                Desktop desktop = Desktop.getDesktop();
                if (desktop.isSupported(Desktop.Action.BROWSE)) {
                    desktop.browse(new URI("https://twitter.com/geovannisans74"));
                }
            }
        } catch (Exception e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_jLTwitterGMouseClicked

    private void jLInstagramGMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLInstagramGMouseClicked
        try {
            if (Desktop.isDesktopSupported()) {
                Desktop desktop = Desktop.getDesktop();
                if (desktop.isSupported(Desktop.Action.BROWSE)) {
                    desktop.browse(new URI("https://www.instagram.com/engelkeinherz/"));
                }
            }
        } catch (Exception e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_jLInstagramGMouseClicked

    private void jBInicioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBInicioActionPerformed
        Inicio inicio = new Inicio();
        timerControl.cancel();
        this.setVisible(false);
        inicio.setVisible(true);
        dispose();
    }//GEN-LAST:event_jBInicioActionPerformed

    private void jLGithubGMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLGithubGMouseClicked
        try {
            if (Desktop.isDesktopSupported()) {
                Desktop desktop = Desktop.getDesktop();
                if (desktop.isSupported(Desktop.Action.BROWSE)) {
                    desktop.browse(new URI("https://github.com/geovanni74"));
                }
            }
        } catch (Exception e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_jLGithubGMouseClicked

    private void jBProduct_OwnerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBProduct_OwnerActionPerformed
        if (jPDesplegableContacto.isVisible()) {
            ContactoProduct_Owner po = new ContactoProduct_Owner();
            timerControl.cancel();
            this.setVisible(false);
            po.setVisible(true);
            dispose();
        }
    }//GEN-LAST:event_jBProduct_OwnerActionPerformed

    private void jLFacebookMMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLFacebookMMouseClicked
        try {
            if (Desktop.isDesktopSupported()) {
                Desktop desktop = Desktop.getDesktop();
                if (desktop.isSupported(Desktop.Action.BROWSE)) {
                    desktop.browse(new URI("https://www.facebook.com/marcoantonio.navacruz"));
                }
            }
        } catch (Exception e) {
        }
    }//GEN-LAST:event_jLFacebookMMouseClicked

    private void jLTwitterMMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLTwitterMMouseClicked
        try {
            if (Desktop.isDesktopSupported()) {
                Desktop desktop = Desktop.getDesktop();
                if (desktop.isSupported(Desktop.Action.BROWSE)) {
                    desktop.browse(new URI("https://twitter.com/MarkoNava1"));
                }
            }
        } catch (Exception e) {
        }
    }//GEN-LAST:event_jLTwitterMMouseClicked

    private void jLGithubMMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLGithubMMouseClicked
        try {
            if (Desktop.isDesktopSupported()) {
                Desktop desktop = Desktop.getDesktop();
                if (desktop.isSupported(Desktop.Action.BROWSE)) {
                    desktop.browse(new URI("https://github.com/Marineford2410"));
                }
            }
        } catch (Exception e) {
        }
    }//GEN-LAST:event_jLGithubMMouseClicked

    private void jBDAgilActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBDAgilActionPerformed
        if (jPDesplegableDAScrum.isVisible()) {
            Agil agil = new Agil();
            timerControl.cancel();
            this.setVisible(false);
            agil.setVisible(true);
            dispose();
        }
    }//GEN-LAST:event_jBDAgilActionPerformed

    private void jBScrumActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBScrumActionPerformed
        if (jPDesplegableDAScrum.isVisible()) {
            Scrum scrum = new Scrum();
            timerControl.cancel();
            this.setVisible(false);
            scrum.setVisible(true);
            dispose();
        }
    }//GEN-LAST:event_jBScrumActionPerformed

    private void jBScrum_MasterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBScrum_MasterActionPerformed
        if (jPDesplegableContacto.isVisible()) {
            ContactoScrum_Master csm = new ContactoScrum_Master();
            timerControl.cancel();
            this.setVisible(false);
            csm.setVisible(true);
            dispose();
        }
    }//GEN-LAST:event_jBScrum_MasterActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ContactoScrum_Team.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ContactoScrum_Team.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ContactoScrum_Team.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ContactoScrum_Team.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ContactoScrum_Team().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBContacto;
    private javax.swing.JButton jBDA_Scrum;
    private javax.swing.JButton jBDAgil;
    private javax.swing.JButton jBIng_Soft;
    private javax.swing.JButton jBInicio;
    private javax.swing.JButton jBProduct_Owner;
    private javax.swing.JButton jBSalir;
    private javax.swing.JButton jBScrum;
    private javax.swing.JButton jBScrum_Master;
    private javax.swing.JButton jBScrum_Team;
    private javax.swing.JLabel jLCine;
    private javax.swing.JLabel jLDormir;
    private javax.swing.JLabel jLFacebookG;
    private javax.swing.JLabel jLFacebookM;
    private javax.swing.JLabel jLFotoGiovanni;
    private javax.swing.JLabel jLFotoMarco;
    private javax.swing.JLabel jLGames;
    private javax.swing.JLabel jLGithubG;
    private javax.swing.JLabel jLGithubM;
    private javax.swing.JLabel jLGoku;
    private javax.swing.JLabel jLGuitarra;
    private javax.swing.JLabel jLHeader;
    private javax.swing.JLabel jLInstagramG;
    private javax.swing.JLabel jLLMusica;
    private javax.swing.JLabel jLLogoICO;
    private javax.swing.JLabel jLMiembro_Equipo;
    private javax.swing.JLabel jLSpider;
    private javax.swing.JLabel jLTacos;
    private javax.swing.JLabel jLTwitterG;
    private javax.swing.JLabel jLTwitterM;
    private javax.swing.JLabel jLVideoJuegos;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPBarraMenu;
    private javax.swing.JPanel jPDesplegableContacto;
    private javax.swing.JPanel jPDesplegableDAScrum;
    private javax.swing.JPanel jPInformacionGiovanni;
    private javax.swing.JPanel jPInformacionMarco;
    private javax.swing.JPanel jPInformacionProduct_Owner;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPerfilGiovanni;
    private javax.swing.JPanel jPerfilMarco;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables

    public void ponerImagenes(){
        // Logo de ICO
        ImageIcon iconoICO = new ImageIcon(System.getProperty("user.dir") + "/src/aragon/ico/imagenes/inicio/ICO.png");
        Icon logoICO = new ImageIcon(iconoICO.getImage().getScaledInstance(jLLogoICO.getWidth(), jLLogoICO.getHeight(), Image.SCALE_AREA_AVERAGING));
        jLLogoICO.setIcon(logoICO);
        
        // Imagen para el Header
        ImageIcon ImageTitulo = new ImageIcon(System.getProperty("user.dir") + "/src/aragon/ico/imagenes/contacto/equipo.jpg");
        Icon iconTitulo = new ImageIcon(ImageTitulo.getImage().getScaledInstance(jLHeader.getWidth(), jLHeader.getHeight(), Image.SCALE_AREA_AVERAGING));
        jLHeader.setIcon(iconTitulo);
        
        /********** Imagenes ST1 (Giovanni) **********/
        // Foto Giovanni
        ImageIcon ImageGiovanni = new ImageIcon(System.getProperty("user.dir") + "/src/aragon/ico/imagenes/contacto/Giovanni.jpg");
        Icon iconGiovanni = new ImageIcon(ImageGiovanni.getImage().getScaledInstance(jLFotoGiovanni.getWidth(), jLFotoGiovanni.getHeight(), Image.SCALE_AREA_AVERAGING));
        jLFotoGiovanni.setIcon(iconGiovanni);
        
        /***** Imagenes hobibes *****/
        // Cine
        ImageIcon ImageCine= new ImageIcon(System.getProperty("user.dir") + "/src/aragon/ico/imagenes/contacto/cine.png");
        Icon iconCine = new ImageIcon(ImageCine.getImage().getScaledInstance(jLCine.getWidth(), jLCine.getHeight(), Image.SCALE_AREA_AVERAGING));
        jLCine.setIcon(iconCine);
        
        // Tacos
        ImageIcon ImageTacos = new ImageIcon(System.getProperty("user.dir") + "/src/aragon/ico/imagenes/contacto/tacos.gif");
        Icon iconTacos = new ImageIcon(ImageTacos.getImage().getScaledInstance(jLTacos.getWidth(), jLTacos.getHeight(), Image.SCALE_AREA_AVERAGING));
        jLTacos.setIcon(iconTacos);
        
        // Musica
        ImageIcon ImageMusica = new ImageIcon(System.getProperty("user.dir") + "/src/aragon/ico/imagenes/contacto/musica.png");
        Icon iconMusica = new ImageIcon(ImageMusica.getImage().getScaledInstance(jLLMusica.getWidth(), jLLMusica.getHeight(), Image.SCALE_AREA_AVERAGING));
        jLLMusica.setIcon(iconMusica);
    
        // Games
        ImageIcon ImageGames = new ImageIcon(System.getProperty("user.dir") + "/src/aragon/ico/imagenes/contacto/videojuegos.png");
        Icon iconGames= new ImageIcon(ImageGames.getImage().getScaledInstance(jLVideoJuegos.getWidth(), jLVideoJuegos.getHeight(), Image.SCALE_AREA_AVERAGING));
        jLVideoJuegos.setIcon(iconGames);
        
        // Dormir
        ImageIcon ImageDormir = new ImageIcon(System.getProperty("user.dir") + "/src/aragon/ico/imagenes/contacto/dormir.png");
        Icon iconDormir = new ImageIcon(ImageDormir.getImage().getScaledInstance(jLDormir.getWidth(), jLDormir.getHeight(), Image.SCALE_AREA_AVERAGING));
        jLDormir.setIcon(iconDormir);
        
        /***** Redes Sociales *****/
        // 
        ImageIcon ImageFacebook = new ImageIcon(System.getProperty("user.dir") + "/src/aragon/ico/imagenes/contacto/facebook.jpg");
        Icon iconFacebook = new ImageIcon(ImageFacebook.getImage().getScaledInstance(jLFacebookG.getWidth(), jLFacebookG.getHeight(), Image.SCALE_AREA_AVERAGING));
        jLFacebookG.setIcon(iconFacebook);
        
        // Twitter
        ImageIcon ImageTwitter = new ImageIcon(System.getProperty("user.dir") + "/src/aragon/ico/imagenes/contacto/Twitter.png");
        Icon iconTwitter = new ImageIcon(ImageTwitter.getImage().getScaledInstance(jLTwitterG.getWidth(), jLTwitterG.getHeight(), Image.SCALE_AREA_AVERAGING));
        jLTwitterG.setIcon(iconTwitter);
        
        // Instagram
        ImageIcon ImageInstagram = new ImageIcon(System.getProperty("user.dir") + "/src/aragon/ico/imagenes/contacto/Instagram.png");
        Icon iconInstagram = new ImageIcon(ImageInstagram.getImage().getScaledInstance(jLInstagramG.getWidth(), jLInstagramG.getHeight(), Image.SCALE_AREA_AVERAGING));
        jLInstagramG.setIcon(iconInstagram);
        
        // Github
        ImageIcon ImageGithub = new ImageIcon(System.getProperty("user.dir") + "/src/aragon/ico/imagenes/contacto/GithubIcon.png");
        Icon iconGithub = new ImageIcon(ImageGithub.getImage().getScaledInstance(jLGithubG.getWidth(), jLGithubG.getHeight(), Image.SCALE_AREA_AVERAGING));
        jLGithubG.setIcon(iconGithub);
    
        
        /********** Imagenes ST1 (Marco) **********/
        // Foto Marco
        ImageIcon ImageMarco = new ImageIcon(System.getProperty("user.dir") + "/src/aragon/ico/imagenes/contacto/Marco.jpg");
        Icon iconMarco = new ImageIcon(ImageMarco.getImage().getScaledInstance(jLFotoMarco.getWidth(), jLFotoMarco.getHeight(), Image.SCALE_AREA_AVERAGING));
        jLFotoMarco.setIcon(iconMarco);
        
        /***** Imagenes hobibes *****/
        // Goku
        ImageIcon ImageGoku = new ImageIcon(System.getProperty("user.dir") + "/src/aragon/ico/imagenes/contacto/Goku.png");
        Icon iconGoku = new ImageIcon(ImageGoku.getImage().getScaledInstance(jLGoku.getWidth(), jLGoku.getHeight(), Image.SCALE_AREA_AVERAGING));
        jLGoku.setIcon(iconGoku);
        
        // Spider
        ImageIcon ImageSpider = new ImageIcon(System.getProperty("user.dir") + "/src/aragon/ico/imagenes/contacto/comic.png");
        Icon iconSpider = new ImageIcon(ImageSpider.getImage().getScaledInstance(jLSpider.getWidth(), jLSpider.getHeight(), Image.SCALE_AREA_AVERAGING));
        jLSpider.setIcon(iconSpider);
        
        // Guitarra
        jLGuitarra.setIcon(iconMusica);
    
        // Games
        jLGames.setIcon(iconGames);
        
        /***** Redes Sociales *****/
        // Facebook
        jLFacebookM.setIcon(iconFacebook);
        
        // Twitter
        jLTwitterM.setIcon(iconTwitter);
        
        // Github
        jLGithubM.setIcon(iconGithub);
    
    }
    
    public void controlDesplegable(){
        int lapso = 1000;
        
        controlmenu = new TimerTask() {
            @Override
            public void run() {
                if (jPDesplegableDAScrum.isVisible() && jPDesplegableDAScrum.getY() < 90) {
                    jPDesplegableDAScrum.setVisible(false);
                }
                
                if (jPDesplegableContacto.isVisible() && jPDesplegableContacto.getY() < 90) {
                    jPDesplegableContacto.setVisible(false);
                }
            }
        };
        
        timerControl = new Timer();
        timerControl.scheduleAtFixedRate(controlmenu, lapso, 1000);
    }
}
