/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package aragon.ico;

import java.awt.Color;
import java.awt.Image;
import java.util.Timer;
import java.util.TimerTask;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import Animacion.Animacion;
import aragon.ico.contacto.ContactoProduct_Owner;

/**
 *
 * @author makin
 */
public class Inicio extends javax.swing.JFrame {

    Timer timerImagenes, timerControl;
    TimerTask cambioDeImagen, controlmenu;
    ImageIcon imagenes;
    Icon slade;
    int indice = 1;

    /**
     * Creates new form Inicio
     */
    public Inicio() {
        initComponents();

        setIconImage(new ImageIcon(getClass().getResource("/aragon/ico/scrum/imagenes/ICO.png")).getImage());

        // La ventana se centrará en medio de la pantalla
        this.setLocationRelativeTo(null);

        // Configuracion de los menus desplegables
        jPDesplegableScrum.setVisible(false);
        jPDesplegableContacto.setVisible(false);

        // Logos de la UNAM FES Aragon y de ICO
        ImageIcon iconoUNAM = new ImageIcon(System.getProperty("user.dir") + "/src/aragon/ico/imagenes/inicio/Aragon.jpg");
        Icon logoUNAM = new ImageIcon(iconoUNAM.getImage().getScaledInstance(jLLogoUNAM.getWidth(), jLLogoUNAM.getHeight(), Image.SCALE_AREA_AVERAGING));
        jLLogoUNAM.setIcon(logoUNAM);

        ImageIcon iconoICO = new ImageIcon(System.getProperty("user.dir") + "/src/aragon/ico/imagenes/inicio/ICO.png");
        Icon logoICO = new ImageIcon(iconoICO.getImage().getScaledInstance(jLLogoICO.getWidth(), jLLogoICO.getHeight(), Image.SCALE_AREA_AVERAGING));
        jLLogoICO.setIcon(logoICO);

        // Imagen con el cual empezará el Slide
        imagenes = new ImageIcon(System.getProperty("user.dir") + "/src/aragon/ico/imagenes/inicio/ing_soft.png");
        slade = new ImageIcon(imagenes.getImage().getScaledInstance(jLSlide.getWidth(), jLSlide.getHeight(), Image.SCALE_AREA_AVERAGING));
        jLSlide.setIcon(slade);

        // Imagen con los reloes de Sccrum
        ImageIcon iconoSCRUM = new ImageIcon(System.getProperty("user.dir") + "/src/aragon/ico/imagenes/inicio/Scrum-roles.jpg");
        Icon logoSCRUM = new ImageIcon(iconoSCRUM.getImage().getScaledInstance(jLSCRUM.getWidth(), jLSCRUM.getHeight(), Image.SCALE_AREA_AVERAGING));
        jLSCRUM.setIcon(logoSCRUM);

        //Imagenes con los isotipos de Github y Trello
        ImageIcon iconoGithub = new ImageIcon(System.getProperty("user.dir") + "/src/aragon/ico/imagenes/inicio/github-logo.png");
        Icon logoGuthub = new ImageIcon(iconoGithub.getImage().getScaledInstance(jLGithub.getWidth(), jLGithub.getHeight(), Image.SCALE_AREA_AVERAGING));
        jLGithub.setIcon(logoGuthub);

        ImageIcon iconoTrello = new ImageIcon(System.getProperty("user.dir") + "/src/aragon/ico/imagenes/inicio/trello.png");
        Icon logoTrello = new ImageIcon(iconoTrello.getImage().getScaledInstance(jLTrello.getWidth(), jLTrello.getHeight(), Image.SCALE_AREA_AVERAGING));
        jLTrello.setIcon(logoTrello);

        this.repaint();

        cambiarImagen();
        controlDesplegable();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jPanel1 = new javax.swing.JPanel();
        jPTitulo = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLLogoICO = new javax.swing.JLabel();
        jLLogoUNAM = new javax.swing.JLabel();
        jPMenu = new javax.swing.JPanel();
        jBDA_Scrum = new javax.swing.JButton();
        jBIngenieria = new javax.swing.JButton();
        jBContacto = new javax.swing.JButton();
        jBSalir = new javax.swing.JButton();
        jPDesplegableScrum = new javax.swing.JPanel();
        jBAgil = new javax.swing.JButton();
        jBScrum = new javax.swing.JButton();
        jPDesplegableContacto = new javax.swing.JPanel();
        jBProduct_Owner = new javax.swing.JButton();
        jBScrum_Master = new javax.swing.JButton();
        jBScrum_Team = new javax.swing.JButton();
        jPContenido = new javax.swing.JPanel();
        jLSlide = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLSCRUM = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLGithub = new javax.swing.JLabel();
        jLTrello = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Inicio");
        setUndecorated(true);
        setResizable(false);

        jScrollPane1.setBorder(null);
        jScrollPane1.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPTitulo.setBackground(new java.awt.Color(255, 255, 255));
        jPTitulo.setForeground(new java.awt.Color(255, 255, 255));

        jLabel1.setFont(new java.awt.Font("Arial Black", 0, 72)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(17, 134, 198));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Inicio");

        javax.swing.GroupLayout jPTituloLayout = new javax.swing.GroupLayout(jPTitulo);
        jPTitulo.setLayout(jPTituloLayout);
        jPTituloLayout.setHorizontalGroup(
            jPTituloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPTituloLayout.createSequentialGroup()
                .addGap(61, 61, 61)
                .addComponent(jLLogoICO, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(38, 38, 38)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 680, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(41, 41, 41)
                .addComponent(jLLogoUNAM, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(60, Short.MAX_VALUE))
        );
        jPTituloLayout.setVerticalGroup(
            jPTituloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPTituloLayout.createSequentialGroup()
                .addContainerGap(20, Short.MAX_VALUE)
                .addGroup(jPTituloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(jLLogoUNAM, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLLogoICO, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20))
        );

        jPanel1.add(jPTitulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1200, 200));

        jPMenu.setBackground(new java.awt.Color(245, 245, 245));

        jBDA_Scrum.setFont(new java.awt.Font("Berlin Sans FB", 0, 24)); // NOI18N
        jBDA_Scrum.setForeground(java.awt.Color.gray);
        jBDA_Scrum.setText("Desarrollo Ágil y Scrum");
        jBDA_Scrum.setBorder(null);
        jBDA_Scrum.setBorderPainted(false);
        jBDA_Scrum.setContentAreaFilled(false);
        jBDA_Scrum.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jBDA_Scrum.setFocusPainted(false);
        jBDA_Scrum.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jBDA_ScrumMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jBDA_ScrumMouseExited(evt);
            }
        });
        jBDA_Scrum.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBDA_ScrumActionPerformed(evt);
            }
        });

        jBIngenieria.setFont(new java.awt.Font("Berlin Sans FB", 0, 24)); // NOI18N
        jBIngenieria.setForeground(java.awt.Color.gray);
        jBIngenieria.setText("Ingeniería de Software");
        jBIngenieria.setBorder(null);
        jBIngenieria.setBorderPainted(false);
        jBIngenieria.setContentAreaFilled(false);
        jBIngenieria.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jBIngenieria.setFocusPainted(false);
        jBIngenieria.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jBIngenieriaMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jBIngenieriaMouseExited(evt);
            }
        });
        jBIngenieria.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBIngenieriaActionPerformed(evt);
            }
        });

        jBContacto.setFont(new java.awt.Font("Berlin Sans FB", 0, 24)); // NOI18N
        jBContacto.setForeground(java.awt.Color.gray);
        jBContacto.setText("Contacto");
        jBContacto.setBorder(null);
        jBContacto.setBorderPainted(false);
        jBContacto.setContentAreaFilled(false);
        jBContacto.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jBContacto.setFocusPainted(false);
        jBContacto.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jBContactoMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jBContactoMouseExited(evt);
            }
        });
        jBContacto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBContactoActionPerformed(evt);
            }
        });

        jBSalir.setFont(new java.awt.Font("Berlin Sans FB", 0, 24)); // NOI18N
        jBSalir.setForeground(java.awt.Color.gray);
        jBSalir.setText("Salir");
        jBSalir.setBorder(null);
        jBSalir.setBorderPainted(false);
        jBSalir.setContentAreaFilled(false);
        jBSalir.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jBSalir.setFocusPainted(false);
        jBSalir.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jBSalirMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jBSalirMouseExited(evt);
            }
        });
        jBSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBSalirActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPMenuLayout = new javax.swing.GroupLayout(jPMenu);
        jPMenu.setLayout(jPMenuLayout);
        jPMenuLayout.setHorizontalGroup(
            jPMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPMenuLayout.createSequentialGroup()
                .addGap(263, 263, 263)
                .addComponent(jBIngenieria)
                .addGap(30, 30, 30)
                .addComponent(jBDA_Scrum)
                .addGap(30, 30, 30)
                .addComponent(jBContacto)
                .addGap(30, 30, 30)
                .addComponent(jBSalir)
                .addContainerGap(263, Short.MAX_VALUE))
        );
        jPMenuLayout.setVerticalGroup(
            jPMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPMenuLayout.createSequentialGroup()
                .addContainerGap(24, Short.MAX_VALUE)
                .addGroup(jPMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(jBIngenieria)
                    .addComponent(jBDA_Scrum)
                    .addComponent(jBContacto)
                    .addComponent(jBSalir))
                .addGap(19, 19, 19))
        );

        jPanel1.add(jPMenu, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 200, 1200, 70));

        jPDesplegableScrum.setBackground(new java.awt.Color(245, 245, 245));

        jBAgil.setFont(new java.awt.Font("Berlin Sans FB", 0, 18)); // NOI18N
        jBAgil.setForeground(java.awt.Color.gray);
        jBAgil.setText("Desarrollo Ágil");
        jBAgil.setBorder(null);
        jBAgil.setBorderPainted(false);
        jBAgil.setContentAreaFilled(false);
        jBAgil.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jBAgil.setFocusPainted(false);
        jBAgil.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jBAgil.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jBAgilMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jBAgilMouseExited(evt);
            }
        });

        jBScrum.setFont(new java.awt.Font("Berlin Sans FB", 0, 18)); // NOI18N
        jBScrum.setForeground(java.awt.Color.gray);
        jBScrum.setText("Scrum");
        jBScrum.setBorder(null);
        jBScrum.setBorderPainted(false);
        jBScrum.setContentAreaFilled(false);
        jBScrum.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jBScrum.setFocusPainted(false);
        jBScrum.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jBScrum.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jBScrumMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jBScrumMouseExited(evt);
            }
        });

        javax.swing.GroupLayout jPDesplegableScrumLayout = new javax.swing.GroupLayout(jPDesplegableScrum);
        jPDesplegableScrum.setLayout(jPDesplegableScrumLayout);
        jPDesplegableScrumLayout.setHorizontalGroup(
            jPDesplegableScrumLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPDesplegableScrumLayout.createSequentialGroup()
                .addContainerGap(104, Short.MAX_VALUE)
                .addGroup(jPDesplegableScrumLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jBAgil, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jBScrum, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
        jPDesplegableScrumLayout.setVerticalGroup(
            jPDesplegableScrumLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPDesplegableScrumLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jBAgil)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jBScrum)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel1.add(jPDesplegableScrum, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 200, 240, 70));

        jPDesplegableContacto.setBackground(new java.awt.Color(245, 245, 245));

        jBProduct_Owner.setFont(new java.awt.Font("Berlin Sans FB", 0, 18)); // NOI18N
        jBProduct_Owner.setForeground(java.awt.Color.gray);
        jBProduct_Owner.setText("Product Owner");
        jBProduct_Owner.setBorder(null);
        jBProduct_Owner.setBorderPainted(false);
        jBProduct_Owner.setContentAreaFilled(false);
        jBProduct_Owner.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jBProduct_Owner.setFocusPainted(false);
        jBProduct_Owner.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jBProduct_Owner.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jBProduct_OwnerMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jBProduct_OwnerMouseExited(evt);
            }
        });
        jBProduct_Owner.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBProduct_OwnerActionPerformed(evt);
            }
        });

        jBScrum_Master.setFont(new java.awt.Font("Berlin Sans FB", 0, 18)); // NOI18N
        jBScrum_Master.setForeground(java.awt.Color.gray);
        jBScrum_Master.setText("Scrum Master");
        jBScrum_Master.setBorder(null);
        jBScrum_Master.setBorderPainted(false);
        jBScrum_Master.setContentAreaFilled(false);
        jBScrum_Master.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jBScrum_Master.setFocusPainted(false);
        jBScrum_Master.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jBScrum_Master.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jBScrum_MasterMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jBScrum_MasterMouseExited(evt);
            }
        });

        jBScrum_Team.setFont(new java.awt.Font("Berlin Sans FB", 0, 18)); // NOI18N
        jBScrum_Team.setForeground(java.awt.Color.gray);
        jBScrum_Team.setText("Scrum Team");
        jBScrum_Team.setBorder(null);
        jBScrum_Team.setBorderPainted(false);
        jBScrum_Team.setContentAreaFilled(false);
        jBScrum_Team.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jBScrum_Team.setFocusPainted(false);
        jBScrum_Team.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jBScrum_Team.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jBScrum_TeamMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jBScrum_TeamMouseExited(evt);
            }
        });

        javax.swing.GroupLayout jPDesplegableContactoLayout = new javax.swing.GroupLayout(jPDesplegableContacto);
        jPDesplegableContacto.setLayout(jPDesplegableContactoLayout);
        jPDesplegableContactoLayout.setHorizontalGroup(
            jPDesplegableContactoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPDesplegableContactoLayout.createSequentialGroup()
                .addContainerGap(26, Short.MAX_VALUE)
                .addGroup(jPDesplegableContactoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jBProduct_Owner, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jBScrum_Master, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jBScrum_Team, javax.swing.GroupLayout.Alignment.TRAILING))
                .addContainerGap())
        );
        jPDesplegableContactoLayout.setVerticalGroup(
            jPDesplegableContactoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPDesplegableContactoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jBProduct_Owner)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jBScrum_Master)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jBScrum_Team)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel1.add(jPDesplegableContacto, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 180, 150, 90));

        jPContenido.setBackground(new java.awt.Color(255, 255, 255));

        jLSlide.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        jLabel2.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 24)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Proyecto Final");

        jLabel3.setBackground(new java.awt.Color(255, 255, 255));
        jLabel3.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 20)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(17, 134, 198));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Especificaciones");

        jLabel4.setBackground(new java.awt.Color(255, 255, 255));
        jLabel4.setFont(new java.awt.Font("Berlin Sans FB", 0, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(59, 59, 59));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("Equipo de 5 personas");

        jLabel5.setBackground(new java.awt.Color(255, 255, 255));
        jLabel5.setFont(new java.awt.Font("Berlin Sans FB", 0, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(59, 59, 59));
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("Un Product Owner");

        jLabel6.setBackground(new java.awt.Color(255, 255, 255));
        jLabel6.setFont(new java.awt.Font("Berlin Sans FB", 0, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(59, 59, 59));
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("Scrum Team (3 personas)");

        jLabel7.setBackground(new java.awt.Color(255, 255, 255));
        jLabel7.setFont(new java.awt.Font("Berlin Sans FB", 0, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(59, 59, 59));
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setText("Un Scrum Master");

        jLabel8.setBackground(new java.awt.Color(255, 255, 255));
        jLabel8.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 20)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(17, 134, 198));
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setText("Requerimientos");

        jLabel9.setBackground(new java.awt.Color(255, 255, 255));
        jLabel9.setFont(new java.awt.Font("Berlin Sans FB", 0, 18)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(59, 59, 59));
        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel9.setText("Gestionar el contenido por medio de Github");

        jLabel10.setBackground(new java.awt.Color(255, 255, 255));
        jLabel10.setFont(new java.awt.Font("Berlin Sans FB", 0, 18)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(59, 59, 59));
        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel10.setText("Coordinación de los avances tiene que ser por medio de la herramienta Trello");

        javax.swing.GroupLayout jPContenidoLayout = new javax.swing.GroupLayout(jPContenido);
        jPContenido.setLayout(jPContenidoLayout);
        jPContenidoLayout.setHorizontalGroup(
            jPContenidoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPContenidoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPContenidoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 1169, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLSCRUM, javax.swing.GroupLayout.PREFERRED_SIZE, 433, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10, javax.swing.GroupLayout.DEFAULT_SIZE, 1180, Short.MAX_VALUE)
                    .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 1169, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPContenidoLayout.createSequentialGroup()
                        .addComponent(jLGithub, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(92, 92, 92)
                        .addComponent(jLTrello, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLSlide, javax.swing.GroupLayout.PREFERRED_SIZE, 800, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(10, 10, 10))
        );
        jPContenidoLayout.setVerticalGroup(
            jPContenidoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPContenidoLayout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addComponent(jLSlide, javax.swing.GroupLayout.PREFERRED_SIZE, 450, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(44, 44, 44)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel4)
                .addGap(5, 5, 5)
                .addComponent(jLabel5)
                .addGap(4, 4, 4)
                .addComponent(jLabel7)
                .addGap(4, 4, 4)
                .addComponent(jLabel6)
                .addGap(18, 18, 18)
                .addComponent(jLSCRUM, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27)
                .addComponent(jLabel8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel9)
                .addGap(5, 5, 5)
                .addComponent(jLabel10)
                .addGap(18, 18, 18)
                .addGroup(jPContenidoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(jLGithub, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLTrello, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel1.add(jPContenido, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 270, 1200, 1110));

        jScrollPane1.setViewportView(jPanel1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 720, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jBDA_ScrumMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBDA_ScrumMouseEntered
        jBDA_Scrum.setForeground(Color.DARK_GRAY);
    }//GEN-LAST:event_jBDA_ScrumMouseEntered

    private void jBDA_ScrumMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBDA_ScrumMouseExited
        jBDA_Scrum.setForeground(Color.GRAY);
    }//GEN-LAST:event_jBDA_ScrumMouseExited

    private void jBIngenieriaMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBIngenieriaMouseEntered
        jBIngenieria.setForeground(Color.DARK_GRAY);
    }//GEN-LAST:event_jBIngenieriaMouseEntered

    private void jBIngenieriaMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBIngenieriaMouseExited
        jBIngenieria.setForeground(Color.GRAY);
    }//GEN-LAST:event_jBIngenieriaMouseExited

    private void jBContactoMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBContactoMouseEntered
        jBContacto.setForeground(Color.DARK_GRAY);
    }//GEN-LAST:event_jBContactoMouseEntered

    private void jBContactoMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBContactoMouseExited
        jBContacto.setForeground(Color.GRAY);
    }//GEN-LAST:event_jBContactoMouseExited

    private void jBAgilMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBAgilMouseEntered
        if (jPDesplegableScrum.isVisible()) {
            jBAgil.setForeground(Color.DARK_GRAY);
        }
    }//GEN-LAST:event_jBAgilMouseEntered

    private void jBAgilMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBAgilMouseExited
        if (jPDesplegableScrum.isVisible()) {
            jBAgil.setForeground(Color.GRAY);
        }
    }//GEN-LAST:event_jBAgilMouseExited

    private void jBScrumMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBScrumMouseEntered
        if (jPDesplegableScrum.isVisible()) {
            jBScrum.setForeground(Color.DARK_GRAY);
        }
    }//GEN-LAST:event_jBScrumMouseEntered

    private void jBScrumMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBScrumMouseExited
        if (jPDesplegableScrum.isVisible()) {
            jBScrum.setForeground(Color.GRAY);
        }
    }//GEN-LAST:event_jBScrumMouseExited

    private void jBProduct_OwnerMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBProduct_OwnerMouseEntered
        if (jPDesplegableContacto.isVisible()) {
            jBProduct_Owner.setForeground(Color.DARK_GRAY);
        }
    }//GEN-LAST:event_jBProduct_OwnerMouseEntered

    private void jBProduct_OwnerMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBProduct_OwnerMouseExited
        if (jPDesplegableContacto.isVisible()) {
            jBProduct_Owner.setForeground(Color.GRAY);
        }
    }//GEN-LAST:event_jBProduct_OwnerMouseExited

    private void jBScrum_MasterMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBScrum_MasterMouseEntered
        if (jPDesplegableContacto.isVisible()) {
            jBScrum_Master.setForeground(Color.DARK_GRAY);
        }
    }//GEN-LAST:event_jBScrum_MasterMouseEntered

    private void jBScrum_MasterMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBScrum_MasterMouseExited
        if (jPDesplegableContacto.isVisible()) {
            jBScrum_Master.setForeground(Color.GRAY);
        }
    }//GEN-LAST:event_jBScrum_MasterMouseExited

    private void jBScrum_TeamMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBScrum_TeamMouseEntered
        if (jPDesplegableContacto.isVisible()) {
            jBScrum_Team.setForeground(Color.DARK_GRAY);
        }
    }//GEN-LAST:event_jBScrum_TeamMouseEntered

    private void jBScrum_TeamMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBScrum_TeamMouseExited
        if (jPDesplegableContacto.isVisible()) {
            jBScrum_Team.setForeground(Color.GRAY);
        }
    }//GEN-LAST:event_jBScrum_TeamMouseExited

    private void jBDA_ScrumActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBDA_ScrumActionPerformed
        int posicion = jPDesplegableScrum.getY();
        if (posicion < 270) {
            if (jPDesplegableContacto.isVisible()) {
                jPDesplegableContacto.setVisible(false);
            }
            jPDesplegableScrum.setVisible(true);
            Animacion.bajar(200, 270, 1, jPDesplegableScrum);
        } else {
            Animacion.subir(270, 200, 1, jPDesplegableScrum);
            jPDesplegableScrum.setVisible(false);
        }
    }//GEN-LAST:event_jBDA_ScrumActionPerformed

    private void jBContactoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBContactoActionPerformed
        int posicion = jPDesplegableContacto.getY();
        if (posicion < 270) {
            if (jPDesplegableScrum.isVisible()) {
                jPDesplegableScrum.setVisible(false);
            }
            jPDesplegableContacto.setVisible(true);
            Animacion.bajar(180, 270, 1, jPDesplegableContacto);
        } else {
            Animacion.subir(270, 180, 1, jPDesplegableContacto);
            jPDesplegableContacto.setVisible(false);
        }
    }//GEN-LAST:event_jBContactoActionPerformed

    private void jBSalirMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBSalirMouseEntered
        jBSalir.setForeground(Color.DARK_GRAY);
    }//GEN-LAST:event_jBSalirMouseEntered

    private void jBSalirMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBSalirMouseExited
        jBSalir.setForeground(Color.GRAY);
    }//GEN-LAST:event_jBSalirMouseExited

    private void jBSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBSalirActionPerformed
        Salida salir = new Salida();
        timerControl.cancel();
        timerImagenes.cancel();
        this.setVisible(false);
        salir.setVisible(true);
        dispose();
    }//GEN-LAST:event_jBSalirActionPerformed

    private void jBIngenieriaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBIngenieriaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jBIngenieriaActionPerformed

    private void jBProduct_OwnerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBProduct_OwnerActionPerformed
        if (jPDesplegableContacto.isVisible()) {
            ContactoProduct_Owner po = new ContactoProduct_Owner();
            timerImagenes.cancel();
            timerControl.cancel();
            this.setVisible(false);
            po.setVisible(true);
            dispose();
        }
            
    }//GEN-LAST:event_jBProduct_OwnerActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Inicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Inicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Inicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Inicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Inicio().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBAgil;
    private javax.swing.JButton jBContacto;
    private javax.swing.JButton jBDA_Scrum;
    private javax.swing.JButton jBIngenieria;
    private javax.swing.JButton jBProduct_Owner;
    private javax.swing.JButton jBSalir;
    private javax.swing.JButton jBScrum;
    private javax.swing.JButton jBScrum_Master;
    private javax.swing.JButton jBScrum_Team;
    private javax.swing.JLabel jLGithub;
    private javax.swing.JLabel jLLogoICO;
    private javax.swing.JLabel jLLogoUNAM;
    private javax.swing.JLabel jLSCRUM;
    private javax.swing.JLabel jLSlide;
    private javax.swing.JLabel jLTrello;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPContenido;
    private javax.swing.JPanel jPDesplegableContacto;
    private javax.swing.JPanel jPDesplegableScrum;
    private javax.swing.JPanel jPMenu;
    private javax.swing.JPanel jPTitulo;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables

    public void cambiarImagen() {
        int velocidad = 3;
        int valMil = velocidad * 1000;

        cambioDeImagen = new TimerTask() {
            @Override
            public void run() {
                switch (indice) {
                    case 0:
                        indice = 1;
                        imagenes = new ImageIcon(System.getProperty("user.dir") + "/src/aragon/ico/imagenes/inicio/ing_soft.png");
                        slade = new ImageIcon(imagenes.getImage().getScaledInstance(jLSlide.getWidth(), jLSlide.getHeight(), Image.SCALE_AREA_AVERAGING));
                        jLSlide.setIcon(slade);
                        break;

                    case 1:
                        indice = 2;
                        imagenes = new ImageIcon(System.getProperty("user.dir") + "/src/aragon/ico/imagenes/inicio/dashboard.jpg");
                        slade = new ImageIcon(imagenes.getImage().getScaledInstance(jLSlide.getWidth(), jLSlide.getHeight(), Image.SCALE_AREA_AVERAGING));
                        jLSlide.setIcon(slade);
                        break;

                    case 2:
                        indice = 3;
                        imagenes = new ImageIcon(System.getProperty("user.dir") + "/src/aragon/ico/imagenes/inicio/desarrollo_ágil.jpg");
                        slade = new ImageIcon(imagenes.getImage().getScaledInstance(jLSlide.getWidth(), jLSlide.getHeight(), Image.SCALE_AREA_AVERAGING));
                        jLSlide.setIcon(slade);
                        break;

                    case 3:
                        indice = 0;
                        imagenes = new ImageIcon(System.getProperty("user.dir") + "/src/aragon/ico/imagenes/inicio/team.png");
                        slade = new ImageIcon(imagenes.getImage().getScaledInstance(jLSlide.getWidth(), jLSlide.getHeight(), Image.SCALE_AREA_AVERAGING));
                        jLSlide.setIcon(slade);
                        break;
                }

                jPanel1.repaint();
            }
        };

        timerImagenes = new Timer();
        timerImagenes.scheduleAtFixedRate(cambioDeImagen, valMil, valMil);

    }

    public void controlDesplegable() {
        int lapso = 1000;

        controlmenu = new TimerTask() {
            @Override
            public void run() {
                if (jPDesplegableScrum.isVisible() && jPDesplegableScrum.getY() < 270) {
                    jPDesplegableScrum.setVisible(false);
                }

                if (jPDesplegableContacto.isVisible() && jPDesplegableContacto.getY() < 270) {
                    jPDesplegableContacto.setVisible(false);
                }
            }
        };

        timerControl = new Timer();
        timerControl.scheduleAtFixedRate(controlmenu, lapso, 1100);
    }
}
